export const HOME_SCREEN = "HOME_SCREEN";
export const CART_SCREEN = "CART_SCREEN";
export const DETAILS_SCREEN = "DETAILS_SCREEN";
export const FAVOURITES_SCREEN = "FAVOURITES_SCREEN";
export const ORDER_HISTORY_SCREEN = "ORDER_HISTORY_SCREEN";
export const PAYMENT_SCREEN = "PAYMENT_SCREEN";

export const BOTTOM_TAB = "BOTTOM_TAB";
